language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies.
install:
  - pip install pytest pytest-cov
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
  - pytest --cov=solutions -v